import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '~/styles/Home.module.css'
import getConfig from 'next/config'
import { useEffect } from 'react'

const { publicRuntimeConfig } = getConfig()

const Home: NextPage = () => {
  useEffect(() => {
    console.log('runtime config:', publicRuntimeConfig)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Next App Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>welcome to Next App Starter!</h1>
      </main>
    </div>
  )
}

export default Home
