import Head from 'next/head'
import styles from '~/styles/Home.module.css'

const DefaultLayout = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>welcome to Next App Starter!</h1>

        {children}
      </main>
    </div>
  )
}

export default DefaultLayout
