import Head from 'next/head'
import type { ReactNode } from 'react'
import AppBar from './AppBar'
import MuiBox from '@mui/material/Box'
import MuiContainer from '@mui/material/Container'
import MuiStack from '@mui/material/Stack'
import settings from '~/settings'

type LayoutProps = {
  children?: ReactNode
}

const DefaultLayout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{settings.appName}</title>
        <meta name="description" content="Generated by next app starter" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MuiBox>
        <AppBar></AppBar>

        <MuiContainer>
          <MuiStack my={4}>{children}</MuiStack>
        </MuiContainer>
      </MuiBox>
    </>
  )
}

export default DefaultLayout
