import Head from 'next/head'
import type { ReactNode } from 'react'

const DefaultLayout = ({ children }: { children?: ReactNode }) => {
  return (
    <>
      <div>
        <Head>
          <title>Next App Starter</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1 className="app-title">welcome to Next App Starter</h1>

          {children}
        </main>
      </div>

      <style jsx>{`
        .app-title {
          text-align: center;
        }
      `}</style>
    </>
  )
}

export default DefaultLayout
